### ISSUE TITLE
Configure JSON env variable create-missing

### ISSUE THREAD

**Issue by TjeuKayim** [rust-lang/mdBook#1036]
In my CI/CD build pipeline, I need to disable `build.create_missing`.
An environment variable `MDBOOK_BUILD__CREATE_MISSING` produces the expected result:
```
$ MDBOOK_BUILD__CREATE_MISSING=false mdbook build
2019-09-25 09:56:30 [ERROR] (mdbook::utils): Error: Chapter file not found, ./mis.md
2019-09-25 09:56:30 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```
However, when using JSON, the configuration gets ignored:
```
$ MDBOOK_BUILD="{'create-missing': false}" mdbook build
2019-09-25 09:59:25 [INFO] (mdbook::book): Book building has started
2019-09-25 09:59:26 [INFO] (mdbook::book): Running the html backend
```
Other configuration parameters as JSON work as expected, like `MDBOOK_OUTPUT__LINKCHECK='{"follow-web-links": true}'`.

So, why is `MDBOOK_BUILD="{'create-missing': false}"` ignored?

`mdbook --version v0.3.1`

**Comment by ehuss** [comment]
There are a few issues here.

One is that your example is not passing valid JSON.  Strings need to be in double quotes, like:

```
MDBOOK_BUILD='{"create-missing": false}'
```

It should probably have some warnings about this.

Next is that it is not doing kebab-case translation to underscores, so that won't work, either.

Finally, the config structures aren't designed to be partially filled (it assumes certain defaults, like the `build.html` table needs to exist).  So anything that touches config will need to assume that any key may be missing (or rewrite the environment key stuff to merge the settings with the default structure, which may be better).

**Comment by TjeuKayim** [comment]
Thanks for the explanation. 
Though it is invalid JSON, the documentation use single quotes at https://rust-lang-nursery.github.io/mdBook/format/config.html#environment-variables.
I tried using single quotes, double quotes, underscore instead of dash. It doesn't seem to have any effect.

**Comment by TjeuKayim** [comment]
9764f8886bcf2d19c3f3eee0614ee93ec27d7adb updated the documentation
