### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/mdBook#1080]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by steveklabnik** [comment]
I've been meaning to do this, but needed to take some time to make sure stuff won't break.

Given that I'm on core, I should be able to do this myself, I'd imagine.

I'll take some time to investigate this week.

**Comment by ehuss** [comment]
Sounds good to me.  

From what I understand github pages are *not* redirected, so we'll need to update the README link and a few places in the code that reference rust-lang.nursery.github.io.  I think most other links are redirected?  It looks like releases should be redirected, which is probably one of the few things that matters since that could break outside user's CI.

I think the deploy key *may* need to be updated for CI.  That will require someone (probably pietroalbini?) to regenerate the key and encrypt it and update the "Secrets" in the GitHub settings.  I'm not sure about that.

Otherwise, CI should "just work" since it migrated to GitHub Actions.  I can't think of anything else that would break.

**Comment by steveklabnik** [comment]
I'm gonna give this one a go now, let's see how it goes.

> From what I understand github pages are not redirected, so we'll need to update the README link and a few places in the code that reference rust-lang.nursery.github.io. I think most other links are redirected? It looks like releases should be redirected, which is probably one of the few things that matters since that could break outside user's CI.

Yes, I think that's true.

> I think the deploy key may need to be updated for CI. That will require someone (probably pietroalbini?) to regenerate the key and encrypt it and update the "Secrets" in the GitHub settings. I'm not sure about that.

I'm going to 

1. move the repo
2. push a commit updating the README
3. see if that breaks CI or not

And we'll go from there. :)

**Comment by steveklabnik** [comment]
So, one wrinkle: while actions are enabled for the org, they also need to be turned on per-repo. As such, I had to close my first PR and then open a new one. But it looks like they're working just fine.

We'll need to cut a release in order to update the links on crates.io.  @ehuss maybe you want to give that a try? That would also exercise the "release" action, which is the only thing that wouldn't have been tested yet, as far as I can tell.

**Comment by ehuss** [comment]
v0.3.4 has been published with all the links updated.  The deploy key somehow magically worked.  Thanks @steveklabnik!

**Comment by steveklabnik** [comment]
Amazing! Thanks so much :)
