### ISSUE TITLE
`include` does not work in SUMMARY.md

### ISSUE THREAD

**Issue by EasiestSoft** [rust-lang/mdBook#1116]
I want to split the long list into separate files and then include them into SUMMARY.md, unfortunately, it doesn't work

**Comment by azerupi** [comment]
Hi,
The `include` directive is only available in the markdown files. The SUMMARY.md has a relatively strict format and no pre-processing is performed on it.

I don't think we want to add any pre-processing to the SUMMARY.md file. It would add more complexity for little gain, but that is my opinion.

If you really have summary files that are that long, I would suggest to create a small script to concatenate the split up summaries together before building the book.

**Comment by jimzcc** [comment]
just tried and it's still true.
would be good if `SUMMARY.md` allowed including files so that a lengthy chapter list can be managed in separate files.

**Comment by nicholashaydensmith** [comment]
+1 for this feature, I think it'd be the most natural way to support auto-generated documentation.  One could autogen a whole tree of md's and then a snippet TOC that gets included in SUMMARY.md.  Not having this feature feels artificially limiting and inconsistent since it's an exception to the feature support of all other mds.
