### ISSUE TITLE
It there any plan for gitbook-like comment system?

### ISSUE THREAD

**Issue by huangjj27** [rust-lang/mdBook#1129]
I'm going to rewrite my posts with markdown, and tend to use mdbook, but I want some comment system so that I could get response from my readers. It there any plan?

**Comment by segfaultsourcery** [comment]
I can't give a definite answer to this, because I don't know, but I don't _think_ there will be one any time soon because books are static. It should still be possible to add a [third party comment section](https://medium.com/level-up-web/most-popular-3rd-party-comment-systems-for-your-website-9f4329a4c6bf), however.

**Comment by huangjj27** [comment]
> It should still be possible to add a third party comment section, however.

thanks! That would be good enough
