### ISSUE TITLE
Scrollbars are weird in Safari

### ISSUE THREAD

**Issue by arniu** [rust-lang/mdBook#1483]
<img width="1280" alt="图片" src="https://user-images.githubusercontent.com/1286674/110286020-294a2a80-801f-11eb-9c1e-c278b67c8a8a.png">

**Comment by ehuss** [comment]
Can you say more what is "weird" about it?

**Comment by arniu** [comment]
The scrollbars are always present.

**Comment by julianfortune** [comment]
The scroll bars:
- Are blocky instead of round
- Are far wider than normal
- Have the same background as the main content in the sidebar which looks incredibly janky
- Do not disappear when not scrolling
- Displace the context horizontally, messing up the alignment of the page (see red annotations)

### Firefox

<img width="1641" alt="Screen Shot 2022-12-21 at 5 47 03 PM" src="https://user-images.githubusercontent.com/25210657/209037264-10b63034-405f-426b-b06a-0da38a148869.png">

### Safari

<img width="1728" alt="Screen Shot 2022-12-21 at 5 47 14 PM" src="https://user-images.githubusercontent.com/25210657/209037281-efd36897-86ad-46e1-be51-45db3aa182e9.png">


The visual weirdness of the scrollbars is super janky and off-putting, and this visual glitch is sufficient to make me not want to use mdBook. I'll see if I can make a minimal reproducible example or something later

**Comment by julianfortune** [comment]
<img width="1174" alt="Screenshot 2022-12-21 at 9 53 48 PM" src="https://user-images.githubusercontent.com/25210657/209067132-6fe44cc4-eaff-472c-bf38-171179543b57.png">

Yeah, so deleting all the chrome CSS for `::-webkit-scrollbar` fixes the issue alright, but also has the effect of making the sidebar scrollbar appear darkened.

**Comment by noritada** [comment]
I had looked into this problem some time ago and found a solution to thin the scrollbars for the time being, so I sent a PR. However, this PR may not be a complete solution, since it does not turn off the scrollbars when they are not needed.

**Comment by julianfortune** [comment]
I just noticed the Jekyll theme Just the Docs (with the dark color theme) renders the side bar with a dark scroll bar—it appears this is the expected behavior for scroll areas within a page in Safari and not an issue that needs to be corrected.

<img width="1205" alt="just-the-docs-scrollbar" src="https://user-images.githubusercontent.com/25210657/211093052-6c8cfa0a-0e0e-403d-814b-f625277d42e5.png">

**Comment by julianfortune** [comment]
@ehuss Do you have context on why the scrollbar styling was added originally? Thanks

**Comment by julianfortune** [comment]
Thanks @ehuss !
