### ISSUE TITLE
hide pages/links in SUMMARY.md

### ISSUE THREAD

**Issue by 221V** [rust-lang/mdBook#1625]
how i can hide (not include, not show) pages/links in SUMMARY.md ?
thanks

**Comment by ehuss** [comment]
All pages must be linked in SUMMARY in order to be included.

**Comment by 221V** [comment]
what if i need that pages, but want not see them in sidebar?

can we add any tag for hide links from sidebar?

**Comment by ehuss** [comment]
That is currently not possible.  There are issues #830 and #702 tracking that kind of request, but for the most part it is intentional.  If you just want to condense the TOC, you can try out the `fold` functionality described at https://rust-lang.github.io/mdBook/format/configuration/renderers.html.

**Comment by 221V** [comment]
all links tags stay at page - so fold is not solution for me((

I want to make page more lightweight

**Comment by ehuss** [comment]
Unfortunately that is not possible.  I'm going to close this as a duplicate of the two issues linked above.
