### ISSUE TITLE
404 page does not render with CSS

### ISSUE THREAD

**Issue by DuckEater54** [rust-lang/mdBook#1690]
I have tried the things I can think ofwhich is:
-  adding the `input-404 = "src/404.md"` leading to an error saying it searches for `src/src/404.md`, 
- changing the `"src/404.md"` to just `404.md`, which gives the same result as my fourth test,
- moving the `404.md` to the root directory of the project which gives a different page layout with no CSS
- removing the `input-404` line from `book.toml` and moving the `404.md` into the `src` directory.

None of these give any CSS styling to the 404 page. I have the most recent version of MdBook downloaded from cargo v0.4.13.

**Comment by DuckEater54** [comment]
I'm currently writing in a forked repository from a repository that uses the basic GitHub Pages link. It is at the root of the site and I can't test it out in a proper web environment.

**Comment by ehuss** [comment]
GitHub pages are not normally deployed at the site root unless you are using a custom domain, or are deploying to a user site. For example, mdbook uses [site-url](https://github.com/rust-lang/mdBook/blob/17d1ed3716932222dd05f0cc9cde38d31543de2b/guide/book.toml#L12) so that a url like https://rust-lang.github.io/mdBook/this/does/not/exist works correctly.

Can you provide a reproduction or an example?

**Comment by DuckEater54** [comment]
I'm working on a few small changes to the rg3d-book.github.io page.

**Comment by DuckEater54** [comment]
Okay for some strange reason the 404 page does not show any css or page formatting when using `mdbook build` and opening the `book/404.html` file, but it does show CSS highlighting when using `mdbook serve` and opening a random page that does not exist
