### ISSUE TITLE
SIGSEGV on long line

### ISSUE THREAD

**Issue by tstdin** [rust-lang/mdBook#1735]
Hello,

I have noticed that providing long line of text (around 21 000 characters) crashes the build.

## Steps to reproduce

1. Paste a long line of text into the source Markdown file (generate e.g. with Python `'a' * 21000`)
2. run `mdbook build`
    ```
    mdbook build
    2022-01-29 16:20:21 [INFO] (mdbook::book): Book building has started
    2022-01-29 16:20:21 [INFO] (mdbook::book): Running the html backend
    
    thread 'main' has overflowed its stack
    fatal runtime error: stack overflow
    zsh: IOT instruction (core dumped)  mdbook build
    ```
## Backtrace from rust-gdb

[backtrace.txt](https://github.com/rust-lang/mdBook/files/7964013/backtrace.txt)

**Comment by clarkfw** [comment]
[`serde_json`](https://github.com/serde-rs/json) use a recursive way to serialize field of struct. When the field happens to be a long string, the stack overflows due to too many frames.

**Comment by mattheww** [comment]
Note you need a very long single word to cause this problem; just having a long line won't trigger it.

The crash is caused by the search indexing code trying to create a very deeply nested JSON file (it has a nested object for each letter in the word).

I've filed mattico/elasticlunr-rs#44 about this.
