### ISSUE TITLE
index.html fails to be created silently when there is no prefix chapter

### ISSUE THREAD

**Issue by ohemelaar** [rust-lang/mdBook#1814]
When building a book that has no prefix chapter before other titles are defined in `SUMMARY.md` the `index.html` file isn't built.

Steps to reproduce:
```bash
cd /tmp
mdbook init --ignore git --title 'My Book' my-book
cd my-book
sed -i '3i# Part 1' src/SUMMARY.md
cat src/SUMMARY.md 
# # Summary
# 
# # Part 1
# - [Chapter 1](./chapter_1.md)
mdbook build
ls book/index.html
# ls: cannot access 'book/index.html': No such file or directory
```

The docs say:

> Before the main numbered chapters, prefix chapters **can** be added...

My understanding is that prefix chapters are thus optional, but mdbook doesn't render correctly without them.

**Comment by ISSOtm** [comment]
According to the code, the first item in the book is supposed to be rendered a second time as `index.html` which seems to be undocumented.

My guess as to the cause for this bug is that the first item, if there are no prefix chapters, is the section title. So this should trigger with e.g. a separator as well.
