### ISSUE TITLE
Folding inner nodes in navigation tree

### ISSUE THREAD

**Issue by moretea** [rust-lang/mdBook#187]
Whilst browsing through documentation, I generally like to toggle hide of subchapters by clicking on the title.

**Comment by azerupi** [comment]
Do you mean folding parts of the sidebar? 
I have had a similar idea, but the user would not be able to fold / expand it themselves. Instead, the author would configure a maximum nesting level at which all sub-chapters nested deeper than that level will be folded, except the ones for the current chapter.

I am curious to hear how you would imagine that feature though :)
How would it interact with the links and all?

**Comment by SpireFlux** [comment]
I also think this is a valuable feature.  However clicking on the link title / chapter title to expand/contract the nested links underneath is problematic, because how do you know if you want to expand, or go to that link?

Perhaps adding a small ">" carrot/twirl for things that are nested?  Similar to how OSX shows file structures in finder?

**Comment by azerupi** [comment]
**Note to myself**: Any solution should be applicable and user friendly to mobile users too.

**Comment by xieyuheng** [comment]
I also think is would be a very very valuable feature.

inner node navigation sidebar (or inner sidebar)

just like readthedocs :: https://docs.readthedocs.io/en/latest/index.html

configure-able on how many levels to be showed

**Comment by ehuss** [comment]
I believe this is now implemented by #1027.
