### ISSUE TITLE
[feature request] support the rendering of adding parentheses

### ISSUE THREAD

**Issue by geometryolife** [rust-lang/mdBook#1895]
**This case renders fine:**

![image](https://user-images.githubusercontent.com/54882546/191443989-74ae48c5-05dd-4581-a328-f5eb9e4a89e6.png)
![image](https://user-images.githubusercontent.com/54882546/191443950-7a39acaa-8c87-407b-b207-38680a132581.png)

**But after adding the parentheses it doesn't work:**

![image](https://user-images.githubusercontent.com/54882546/191444532-805f4e5f-b184-4f9a-bbe4-f607ba3514c7.png)
![image](https://user-images.githubusercontent.com/54882546/191444573-f9bc0fca-7bab-4754-aad2-fa4274305ca7.png)

**Comment by ehuss** [comment]
I believe this is working as intended. mdBook uses [CommonMark](https://commonmark.org/), and this seems to be related to a [right-flanking delimiter run](https://spec.commonmark.org/0.30/#right-flanking-delimiter-run). The right emphasis cannot be preceded by a space or a punctuation character, unless it is followed by a space. Try removing the space before the `***` and adding a space after.

Also, when reporting an issue, it can be helpful to include the actual text you are using instead of screenshots. I can't copy and paste your example to show you directly how to fix it.

**Comment by geometryolife** [comment]
@ehuss 
Indeed, as you said, punctuation cannot be used before emphasis. If it is used, a space must be added after emphasis to render properly.
This may be the difference between Chinese and English. Chinese parentheses occupy the position of two English parentheses. If a space is added after the emphasis, the visual effect will not be so good.

```
Chinese：
***结构体（struct）***是包含类型字段的自定义数据结构。结构体可以存储任何非引用类型，包括其他结构。

English：
***结构体(struct)***是包含类型字段的自定义数据结构。结构体可以存储任何非引用类型，包括其他结构。
```
render result:
![image](https://user-images.githubusercontent.com/54882546/191516279-f7a93e54-16d5-4d32-bc63-01129bf531e0.png)

For this reason, I have chosen a compromise:
```
***结构体***（struct）是包含类型字段的自定义数据结构。结构体可以存储任何非引用类型，包括其他结构。
```
![image](https://user-images.githubusercontent.com/54882546/191519712-d2120e5f-8e81-4625-ac6c-c11d4913a1e2.png)

***Thanks for your detailed reply.***

**Comment by ehuss** [comment]
OK, I'm going to go ahead and close since this is just the behavior of markdown. If you want to follow up, I recommend you check if there is already an issue about this on the commonmark spec, and maybe open a new one if not.

**Comment by ehuss** [comment]
Oh, and I forgot to suggest that you can also just use HTML tags if the spacing is an issue.
