### ISSUE TITLE
rustup can show this book but after change color it is not remain for other pages

### ISSUE THREAD

**Issue by esmaeelE** [rust-lang/mdBook#1896]
URL to the section(s) of the book with this problem:
In rustup help command rustup --help we read that run book with rustup doc --book

Description of the problem:
But after run book if change the color it can not remain when open another page on book.

Suggested fix:
It seems related to css issue.

I file a bug in rustup page they say it relates to mdbook.
https://github.com/rust-lang/book/issues/3354#issue-1377421806

**Comment by ehuss** [comment]
The issue is that some browsers have restrictions around how local storage works with `file://` URLs.

`rustup` will likely need to support some kind of local webserver in order to work around that. This is essentially a duplicate of https://github.com/rust-lang/rustup/issues/2151, so closing in favor of that.
