### ISSUE TITLE
About release 0.4.27

### ISSUE THREAD

**Issue by p-linnane** [rust-lang/mdBook#2024]
### Question

Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packing mdBook 0.4.27 we noticed that it is not marked as the latest release on GitHub. Is this accurate?

Relates to https://github.com/Homebrew/homebrew-core/pull/123132

**Comment by ehuss** [comment]
Thanks for the heads up! I updated it so that 0.4.27 is the latest release.

I'm not sure what happened. I published from a different machine than before, and it seems like GitHub defaulted to leaving the "set this as latest" checkbox off by default? I'll be sure to pay attention to that in the future.
