### ISSUE TITLE
Cannot get apple-touch-icon to load up

### ISSUE THREAD

**Issue by joelouthan** [rust-lang/mdBook#2097]
### Question

Hello!

I am trying to envoke an apple-touch-icon.png within [index.hbs](https://github.com/joelouthan/theologicus/blob/0958bbee24b1e7e1204ea07b9b2a2df0bb942af1/theme/index.hbs)

```hbs
        {{#if favicon_apple_touch}}
        <link rel="apple-touch-icon" href="{{ path_to_root }}apple-touch-icon.png">
        {{/if}}
```

What I have done:
- place this snippet in head.hbs
- place this snippet directly into index.hbs
- did so with and without `{{#if favicon_apple_touch}}` (which is something I don't fully understand)

Locally and server side: I see the `favicon.png` and `favicon.svg` show up in `/book` but no `apple-touch-icon.png`.

Thank you.

### Version

```text
mdbook --version
mdbook v0.4.30
```
```

**Comment by joelouthan** [comment]
>This looks like it is missing the >.

caught it. thanks!

>The {{#if favicon_apple_touch}} condition will always be false unless you modified mdbook itself to set that condition.

Is there any chance you could show me how to set that -OR- point me in the right direction?

I take that it is not something I can do within my book?

**Comment by ehuss** [comment]
I'm a little uncertain what you are trying to do. If you just want to add the link to your theme, don't include the `{{#if}}` stuff. That is only necessary so that mdbook can skip adding the favicon links if the files don't exist.  For your theme override, you'll presumably know that the touch favicon is always there, so there's no need to make it conditional.

Also, the image file will need to be in the `src` directory, not the `theme` directory. mdbook only copies specific files from the theme directory (listed [here](https://rust-lang.github.io/mdBook/format/theme/index.html)). It will copy any image file from the `src` directory to the output.

(To answer your question, the conditionals are added [here](https://github.com/rust-lang/mdBook/blob/a204946d39db89db242783afb3f27a0f75189589/src/renderer/html_handlebars/hbs_renderer.rs#L659-L664), but you shouldn't need to change that if you just want to add a link.)

**Comment by joelouthan** [comment]
>Also, the image file will need to be in the src directory, not the theme directory. mdbook only copies specific files from the theme directory (listed [here](https://rust-lang.github.io/mdBook/format/theme/index.html)). It will copy any image file from the src directory to the output.

THAT'S what I was missing.

- place favicons in src
- make sure `theme/index.hbs` has the following snippet:

```hbs
        {{#if favicon_svg}}
        <link rel="icon" href="{{ path_to_root }}favicon.svg">
        {{/if}}
        {{#if favicon_png}}
        <link rel="shortcut icon" href="{{ path_to_root }}favicon.png">
        {{/if}}
        <link rel="apple-touch-icon" href="{{ path_to_root }}apple-touch-icon.png">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ path_to_root }}apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ path_to_root }}favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ path_to_root }}favicon-16x16.png">
        <link rel="manifest" href="{{ path_to_root }}site.webmanifest">
        <link rel="mask-icon" href="{{ path_to_root }}safari-pinned-tab.svg" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#9f00a7">
        <meta name="msapplication-TileImage" content="/mstile-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="{{ path_to_root }}css/variables.css">
        <link rel="stylesheet" href="{{ path_to_root }}css/general.css">
        <link rel="stylesheet" href="{{ path_to_root }}css/chrome.css">
```
