### ISSUE TITLE
how to .. localization ?

### ISSUE THREAD

**Issue by 221V** [rust-lang/mdBook#2363]
### Question

```
{{ theme_option "Light" }}
{{ theme_option "Dark" }}
```
how to set my value (localization instead english) for this key in index.hbs ?

documentation still so poor ((

thank you!

**Comment by ehuss** [comment]
`theme_option` isn't localizable, and will be removed in a future release.

In `index.hbs`, there is a hard-coded list of theme names [here](https://github.com/rust-lang/mdBook/blob/c671c2e90486b6ec72921a5043dac1c1c5565f76/src/theme/index.hbs#L155-L161), which can be modified to be in the language of your choice.

Otherwise, unfortunately, mdbook does not have built-in support for localization. I'm going to close in reference to https://github.com/rust-lang/mdBook/issues/5 where localization support is tracked.
