### ISSUE TITLE
How to prevent the .git directory in the output directory from being deleted？

### ISSUE THREAD

**Issue by phpmooc** [rust-lang/mdBook#2370]
### Question

`mdbook v0.4.37`

As title described , if run the command like `mdbook serve` or `mdbook build`,  I hope that the `.git` directory in the output directory should **NOT** be deleted, what should I do?  

Any help will be appreciated.

**Comment by ehuss** [comment]
The output directory is intended to be ephemeral. You will need to send the output to another directory, and then use some tooling to either copy it into your repository or otherwise initialize it. There are some examples in the wiki, such as https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Pages-%28Deploy-from-branch%29, for doing deployment via git.

**Comment by phpmooc** [comment]
Tks a lot. but it seems so cumbersome and not what I expected,  I found one workaround:  have git in the parent directory.
