### ISSUE TITLE
Editable Rust code

### ISSUE THREAD

**Issue by StefanSalewski** [rust-lang/mdBook#2446]
In the last weeks I was writing some Rust tutorial.

I still have some issues understanding the use of code examples:

For the following, making it editable makes the hidden lines always visible. Is this desired?

```rust,editable
# fn main() {
println!("ddd");
# }
```

And the following example fails to run. Is that desired as well?

```rust,editable
println!("eee");
```

And finally a question about indentation when using hidden lines. Which form of the following two code examples would we typically use in books and tutorials?

```rust
# fn main() {
println!("ddd");
# }
```

```rust
# fn main() {
    println!("ddd");
# }
```

**Comment by ehuss** [comment]
> For the following, making it editable makes the hidden lines always visible. Is this desired?

The editor does not support the ability to have hidden lines.

> And the following example fails to run. Is that desired as well?

Since the editor doesn't support hidden lines, this is isn't supported, see #1767.

> Which form of the following two code examples would we typically use in books and tutorials?

If it is just main (and not editable), I would use neither and just have a single line of `println!`. If it is something more complicated, I would probably not indent the non-hidden lines, but it depends on the circumstance.
