### ISSUE TITLE
Add a linkchecker

### ISSUE THREAD

**Issue by projektir** [rust-lang/mdBook#356]
A linkchecker is a convenient tool to have for avoiding errors and keeping track of dead links. It is also a nice to have for #308.

The RBE linkchecker and the one used in [rust-lang/rust](https://github.com/rust-lang/rust/blob/master/src/tools/linkchecker/main.rs) both scan the files line-by-line while applying a regex to find links and check them. I don't know if it'd be OK for us to adopt the [rust-lang/rust](https://github.com/rust-lang/rust/blob/master/src/tools/linkchecker/main.rs) one? @steveklabnik 

I think a good place for this would be `mdbook test`.

**Comment by Michael-F-Bryan** [comment]
This would be a good candidate for the plugin system (#163). Ideally, after the rendering stage you'd be able to make a plugin which gets passed the rendered output's location and then checks all the links in all the `*.html` files it can find.

We're planning on refactoring the current system to make it a lot easier to write your own plugins and renderers.

**Comment by azerupi** [comment]
>I think a good place for this would be mdbook test

Definitely in `mdbook test`

>This would be a good candidate for the plugin system

I agree, this could potentially be written as a plugin **in the future** :)
I emphasised "in the future" because I don't want to stall progress on changes that are coming *soon-ish*. We don't have a deadline for the plugin system, so if someone wants to contribute a solution right now, I wouldn't want to break their inertia.

However, we can keep this use case in the back of our minds when doing the refactorings, to make it indeed possible to implement this as a plugin later. :)

**Comment by steveklabnik** [comment]
I've thought about trying to put the rust-lang one on crates.io so others
could use it too, to be honest.

**Comment by budziq** [comment]
> Definitely in `mdbook test`

It might be nice to have it as a warning also on `mdbook build` stage 

> I've thought about trying to put the rust-lang one on crates.io so others
could use it too, to be honest.

@steveklabnik That would be awesome!

**Comment by Michael-F-Bryan** [comment]
For anyone interested, I've started playing around with a [mdbook-linkcheck] backend for checking links. You'll need to install `mdbook` directly from `master` and isn't 100% finished yet, but it may be useful for some people.

[mdbook-linkcheck]: https://github.com/Michael-F-Bryan/mdbook-linkcheck

**Comment by projektir** [comment]
@Michael-F-Bryan so [rust-lang/rust](https://github.com/rust-lang/rust) already has a [linkchecker](https://github.com/rust-lang/rust/blob/master/src/tools/linkchecker/main.rs), which is the one we originally wanted to pull out and turn into a crate (I'm not sure what that means for plugins). It has some problems, though, that yours doesn't have (for instance, this [fix](https://github.com/rust-lang/rust/pull/47387) is really needed), but it also does some things yours doesn't (check for absolute paths).

Idk if we want to have these out of sync given that rust-lang/rust's linkchecker would run on every `x.py` build for all the books that it manages.

**Comment by Michael-F-Bryan** [comment]
> Idk if we want to have these out of sync given that rust-lang/rust's linkchecker would run on every x.py build for all the books that it manages.

My original hopes were that this could supplement (or even succeed?) their link checker, although on further inspection they do a lot of cross-site linking (i.e. using links to files outside the book such as ` ../../std/prelude/index.html`). My linkchecker works purely with the source book and doesn't take into account the fact that other things exist on the Rust S3 bucket, so I don't know whether this is still possible.

That said, the entire idea behind enabling alternate backends is that people can write their own tools to suit their exact use case. For example, it was almost trivial to knock up a backend which runs everything through `rust-skeptic`, which is something Rust By Example currently need to do manually.

>  but it also does some things yours doesn't (check for absolute paths).

This part was tricky. I originally treated relative and absolute paths separately (relative links are relative to the chapter's directory, absolute is relative to `src/`) but found that most of the links in Rust By Example used a completely different convention. We use the `<base>` tag to tweak how links get resolved by your browser, so what I detected as a "broken link" turned out to still work fine when viewing online.

**Comment by Michael-F-Bryan** [comment]
@ehuss, the [mdbook-linkcheck](https://crates.io/crates/mdbook-linkcheck) backend already exists and does a pretty good job.

Are we happy with letting the ecosystem provide a linkchecker instead of making it part of `mdbook`?

**Comment by ehuss** [comment]
I think that's up to you!  It seems unlikely that anyone is going to develop a new link checker. If you're asking if you want to migrate mdbook-linkcheck as a built-in, I think that's also up to you.  Or if you're asking if this issue should just be closed, I'm fine with that, too.

**Comment by Michael-F-Bryan** [comment]
I think we can close the issue. The `mdbook-linkcheck` crate should fill this niche well enough.

**Comment by ehuss** [comment]
Sounds reasonable!
