### ISSUE TITLE
breaking styles after change default theme

### ISSUE THREAD

**Issue by ava57r** [rust-lang/mdBook#693]
After change 
https://github.com/rust-lang-nursery/mdBook/commit/f01bf88e69cf84fb253962f5d78b7c5a4eaf8306
https://github.com/rust-lang-nursery/mdBook/commit/f01bf88e69cf84fb253962f5d78b7c5a4eaf8306#diff-9f0d373829e789d9a6923dd290c5b174L21

Missing button icons published on github.com version of the book
![39983012-dcaa8e36-575e-11e8-961a-e0f777513ca9](https://user-images.githubusercontent.com/20382553/39994386-ce684930-5781-11e8-901b-8dc9c02c6ce1.jpg)

Book is here:
https://rurust.github.io/rust-by-example-ru/index.html

**Comment by mattico** [comment]
The problem is that rust-by-example's `theme/index.hbs` hasn't been updated for the latest mdbook changes. I think it would work with 0.1.5 or earlier. The changes I'd suggest:

 - Update RBE to newest mdbook version
 - Change RBE readme instructions to install specific mdbook version

**Comment by mattico** [comment]
Until RBE is updated you can fix this issue by either applying https://github.com/rust-lang/rust-by-example/pull/1080/commits/47987dc058aeed56ecf3299378bbf8da92529900 to your fork, or build it with mdBook 0.1.5.

**Comment by cauebs** [comment]
I've been having this problem as well. What really bugged me was that locally it works fine, but when I push it to Github pages the icons all disappear. I just noticed it's not only me: https://rust-lang-nursery.github.io/edition-guide/

**Comment by mattico** [comment]
@cauebs interesting. I believe the Rust by Example issue is related to the custom theme's index.hbs not being updated for the new mdbook version, but the edition guide doesn't use any custom themeing. Does your book? Perhaps there's some other issue at play.

Downloading a complete copy of the edition from the github pages site, the _FontAwesome directory is completely missing. I assume that, since it works locally, this is a problem related to pages?

**Comment by mattico** [comment]
Ah, okay: https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

> By default, Jekyll does not build any files or directories that
> - are hidden or used for backup (indicated by names that start with . or #, or that end with ~);
> - contain site content (indicated by names that start with _); or
> - are excluded in the site configuration.

To me this doesn't indicate that the not-built files won't end up on the target site, but that is actually the case: https://stackoverflow.com/questions/6397780

You can work around this at the moment by adding a `.nojekyll` file to your built book's root. Since mdBook is often used for github pages, we should fix this behavior.
