### ISSUE TITLE
Migrate from error_chain?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/mdBook#899]
`error_chain` is mostly unmaintained now, I think it would be a good idea to move off it.  I only have experience with `failure`, so that would be my preference as an alternative. But if anyone prefers something else, it would be good to discuss!

**Comment by shepmaster** [comment]
> anyone prefers something else

I'd like to humbly suggest [SNAFU](https://docs.rs/snafu/0.2.2/snafu/). I think it's the bee's knees.

Is there anything concretely disliked about the current implementation that I could watch out for when preparing a PR for discussion?

**Comment by shepmaster** [comment]
Some thoughts on a first skim:

- There are *a lot* of stringly-typed errors; basically any use of `error_chain`:

  ```rust
  utils::fs::remove_dir_content(&build_dir)
      .chain_err(|| "Unable to clear output directory")?;
  ```

- Errors that could provide more information. In the same example, it would be nice to know *what* directory was unable to be cleared.

- Multiple errors don't expose *any* context. For example, I'm pretty sure that this error would be very hard for an end-user to debug, because it's not obvious *why* we are creating a directory:

  ```rust
  if !parent.exists() {
      fs::create_dir_all(parent)?;
  }
  ```

**Comment by shepmaster** [comment]
Does mdBook have a minimum Rust version it targets? I'm seeing a few places that could make use of newer Rust features (like `fs::read_to_*`).

**Comment by shepmaster** [comment]
I've [moved a few modules over to SNAFU](https://github.com/rust-lang-nursery/mdBook/compare/master...integer32llc:snafu?expand=1), if anyone is interested in checking it out or providing early-stage feedback.

**Comment by ehuss** [comment]
Closing as `error_chain` was dropped for `anyhow` in #1211.
